CREATE TABLE IF NOT EXISTS users (
  user_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email     VARCHAR(50) UNIQUE NOT NULL,
  login     VARCHAR(50) UNIQUE NOT NULL,
  user_name VARCHAR(50),
  birthday  DATE
);

CREATE TABLE IF NOT EXISTS statuses (
  status_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS friendships (
  user_id   INTEGER NOT NULL,
  friend_id INTEGER NOT NULL,
  status_id INTEGER NOT NULL,
  PRIMARY KEY (user_id, friend_id, status_id)
);
ALTER TABLE friendships ADD CONSTRAINT fk_user_users      FOREIGN KEY (user_id)   REFERENCES users (user_id);
ALTER TABLE friendships ADD CONSTRAINT fk_friend_users    FOREIGN KEY (friend_id) REFERENCES users (user_id);
ALTER TABLE friendships ADD CONSTRAINT fk_status_statuses FOREIGN KEY (status_id) REFERENCES statuses (status_id);

CREATE TABLE IF NOT EXISTS mpa_ratings (
  rating_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating_name VARCHAR(5) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
  film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_name    VARCHAR(50) UNIQUE NOT NULL,
  description  VARCHAR(200) NOT NULL,
  release_date DATE,
  duration     INTEGER,
  rating_id    INTEGER NOT NULL
);
ALTER TABLE films ADD CONSTRAINT fk_films_ratings FOREIGN KEY (rating_id) REFERENCES mpa_ratings (rating_id);

CREATE TABLE IF NOT EXISTS genres (
  genre_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre_name VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id  INTEGER NOT NULL,
  genre_id INTEGER NOT NULL,
  PRIMARY KEY (film_id, genre_id)
);
ALTER TABLE film_genres ADD CONSTRAINT fk_fg_films   FOREIGN KEY (film_id)  REFERENCES films (film_id);
ALTER TABLE film_genres ADD CONSTRAINT fk_fg_genres FOREIGN KEY (genre_id) REFERENCES genres (genre_id);

CREATE TABLE IF NOT EXISTS film_likes (
  film_id  INTEGER NOT NULL,
  user_id  INTEGER NOT NULL,
  PRIMARY KEY (film_id, user_id)
);
ALTER TABLE film_likes ADD CONSTRAINT fk_fl_films FOREIGN KEY (film_id) REFERENCES films (film_id);
ALTER TABLE film_likes ADD CONSTRAINT fk_fl_users FOREIGN KEY (user_id) REFERENCES users (user_id);